<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    public function run(): void
    {

        // ==========================================
        // 2. MAINTAIN SIANG (30 ITEM)
        // ==========================================
        $maintain_siang = [
            ['nama_menu' => 'Nasi Ayam Tumis Sayur', 'deskripsi' => 'Nasi putih (150g) dengan tumis dada ayam 100g dan sayuran hijau.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 35, 'karbohidrat' => 50, 'lemak' => 15, 'gambar' => 'https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p2/238/2024/12/16/Tumis-Ayam-Bawang-Nasi-Daun-Jeruk-2831462054.jpg'],
            ['nama_menu' => 'Soto Ayam Bening', 'deskripsi' => 'Semangkuk soto ayam bening, sedikit bihun, porsi ayam, dan nasi.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 450, 'protein' => 30, 'karbohidrat' => 45, 'lemak' => 15, 'gambar' => 'https://buckets.sasa.co.id/v1/AUTH_Assets/Assets/p/website/medias/page_medias/Screen_Shot_2021-07-19_at_15_50_56.png'],
            ['nama_menu' => 'Nasi Merah Salmon Panggang', 'deskripsi' => 'Nasi merah dengan fillet salmon panggang 80g dan coleslaw ringan.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 500, 'protein' => 32, 'karbohidrat' => 45, 'lemak' => 20, 'gambar' => 'https://media.istockphoto.com/id/1450377987/id/foto/tusuk-dengan-nasi-merah-salmon-dan-sayuran-panggang.jpg?s=612x612&w=0&k=20&c=LpN8VyYUC6arq1LQJ5N65XP8AyXZyk_KVM6mnhKzwyg='],
            ['nama_menu' => 'Nasi Uduk Ayam Kukus', 'deskripsi' => 'Nasi uduk porsi kecil, ayam kukus, tempe bacem, dan telur rebus.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 530, 'protein' => 28, 'karbohidrat' => 60, 'lemak' => 20, 'gambar' => 'https://media.istockphoto.com/id/1467045611/id/foto/nasi-bakmoy-nasi-kukus-dengan-topping-ayam-manis-dan-gurih.jpg?s=1024x1024&w=is&k=20&c=VRuer8c0rb3g9h3Vac8EG5tNCbVN_k7zVAEwlhjAxXk='],
            ['nama_menu' => 'Gado-Gado Lontong Kecil', 'deskripsi' => 'Gado-gado dengan sayuran lengkap, bumbu kacang porsi sedang, dan lontong kecil.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 490, 'protein' => 18, 'karbohidrat' => 65, 'lemak' => 18, 'gambar' => 'https://segari.id/recipes/gado-gado?srsltid=AfmBOootXGc9Oc1egH7bw7PzXrpWvnSp8fX6sDVHa5yo5viLDpDe6xfy'],
            ['nama_menu' => 'Power Bowl Telur Tahu', 'deskripsi' => 'Nasi merah, 2 telur rebus, tahu panggang, dan brokoli.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 460, 'protein' => 25, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://img-global.cpcdn.com/recipes/110bf8f823ac99ab/1200x630cq80/photo.jpg'],
            ['nama_menu' => 'Nasi Goreng Kampung Sehat', 'deskripsi' => 'Nasi goreng minimalis (minyak sedikit), isian sayur dan udang 50g.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 510, 'protein' => 22, 'karbohidrat' => 60, 'lemak' => 20, 'gambar' => 'https://harvestkitchenbar.com/wp-content/uploads/2025/08/img_xWTu4et.jpg'],
            ['nama_menu' => 'Pasta Pesto Chicken', 'deskripsi' => 'Pasta gandum dengan saus pesto basil dan dada ayam panggang.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 550, 'protein' => 30, 'karbohidrat' => 60, 'lemak' => 25, 'gambar' => 'https://www.budgetbytes.com/wp-content/uploads/2019/10/Creamy-Pesto-Chicken-Pasta-close-plate.jpg'],
            ['nama_menu' => 'Ayam Woku Nasi Kuning', 'deskripsi' => 'Nasi kuning dengan ayam suwir Woku pedas dan tumis buncis.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 470, 'protein' => 30, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTotl9F4TLUj4a7iZp_VXdfpsbT8A6Zz9xjKw&s'],
            ['nama_menu' => 'Beef Teriyaki & Ubi', 'deskripsi' => 'Irisan daging sapi teriyaki dengan ubi jalar rebus dan selada.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 520, 'protein' => 35, 'karbohidrat' => 55, 'lemak' => 20, 'gambar' => 'https://assets.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p3/105/2024/06/20/spicy-beef-teriyaki-donburi_1036998-58085-1289460822.jpg'],
            ['nama_menu' => 'Chicken Caesar Salad with Pita', 'deskripsi' => 'Dada ayam panggang, selada romaine, keju parmesan, dressing caesar ringan, disajikan dengan roti pita gandum kecil.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 38, 'karbohidrat' => 35, 'lemak' => 22, 'gambar' => 'https://www.tasteofhome.com/wp-content/uploads/2025/05/Chicken-Caesar-Pitas_EXPS_TOHD25_156279_JonathanMelendez_02.jpg'],
            ['nama_menu' => 'Kebab Ayam Gandum', 'deskripsi' => 'Tortilla gandum berisi dada ayam panggang, paprika, dan yogurt dressing.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 490, 'protein' => 35, 'karbohidrat' => 45, 'lemak' => 20, 'gambar' => 'https://i0.wp.com/i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/94aeca01-0561-44b1-b2a4-448cb66d4601_b1c528b0-c36e-4ba2-a707-23f912df5595.jpg?resize=728%2C500'],
            ['nama_menu' => 'Quinoa Bowl Mediterranean', 'deskripsi' => 'Quinoa dengan potongan tomat, timun, feta cheese, dan dressing minyak zaitun lemon.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 510, 'protein' => 20, 'karbohidrat' => 55, 'lemak' => 25, 'gambar' => 'https://www.fitmittenkitchen.com/wp-content/uploads/2022/02/Greek-Mediterranean-Quinoa-Power-Bowl-18.jpg'],
            ['nama_menu' => 'Tumis Udang Brokoli', 'deskripsi' => 'Nasi putih dengan tumis udang dan brokoli saus tiram rendah gula.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 25, 'karbohidrat' => 60, 'lemak' => 15, 'gambar' => 'https://cdn0-production-images-kly.akamaized.net/xo8SC3Txb17cyVFP3jP1HzEXQxI=/1200x675/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/4169403/original/002758000_1663984001-fried-broccoli-with-garlic-shrimp-thai-food__1_.jpg'],
            ['nama_menu' => 'Pasta Whole Wheat Aglio Olio Salmon', 'deskripsi' => 'Pasta gandum utuh dengan irisan salmon, minyak zaitun, dan cabai.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 500, 'protein' => 30, 'karbohidrat' => 55, 'lemak' => 20, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1NqKTllJp_a0ecT7T6ojSK5YorBs3EvSg4g&s'],
            ['nama_menu' => 'Nasi Capcay Kuah Seimbang', 'deskripsi' => 'Nasi dengan porsi capcay kuah (ayam, udang, sayur) rendah minyak.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 460, 'protein' => 25, 'karbohidrat' => 55, 'lemak' => 16, 'gambar' => 'https://asset.kompas.com/crops/3aFZWJLthPlwxE9Yyr2QOP5rt4A=/6x2:700x465/375x240/data/photo/2021/11/04/6183c80555018.jpg'],
            ['nama_menu' => 'Ayam Bakar Madu Dada', 'deskripsi' => 'Dada ayam bakar madu dengan nasi merah dan sayur lalap.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 510, 'protein' => 38, 'karbohidrat' => 55, 'lemak' => 18, 'gambar' => 'https://asset.kompas.com/crops/N8WTCiVClutwEkjIgCykYbt1e2Q=/142x72:863x553/1200x800/data/photo/2022/09/27/633297e88244b.jpg'],
            ['nama_menu' => 'Bihun Kuah Bakso Sayur', 'deskripsi' => 'Bihun kuah dengan bakso sapi dan sawi, tanpa minyak bawang berlebih.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 450, 'protein' => 22, 'karbohidrat' => 60, 'lemak' => 15, 'gambar' => 'https://awsimages.detik.net.id/community/media/visual/2022/04/19/resep-bihun-kuah-ayam-suwir_43.jpeg?w=600&q=90'],
            ['nama_menu' => 'Selada Tempe Saus Kacang', 'deskripsi' => 'Selada segar, timun, tomat, dan tempe panggang/kukus, disajikan dengan saus kacang rendah lemak dan gula.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 380, 'protein' => 25, 'karbohidrat' => 30, 'lemak' => 18, 'gambar' => 'https://healthynibblesandbits.com/wp-content/uploads/2018/08/Tempeh-Lettuce-Wraps-4.jpg'],
            ['nama_menu' => 'Wrap Tempe Kacang', 'deskripsi' => 'Tortilla gandum isi tempe panggang, bumbu kacang, dan sayuran coleslaw.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 480, 'protein' => 20, 'karbohidrat' => 60, 'lemak' => 20, 'gambar' => 'https://dietitiandebbie.com/wp-content/uploads/2019/02/Tempeh-Wrap-with-Peanut-Sauce.jpg'],
            ['nama_menu' => 'Tuna Melt Sandwich', 'deskripsi' => 'Dua lembar roti gandum utuh, tuna in water, low-fat keju, dan mustard. Disajikan dengan salad samping.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 450, 'protein' => 30, 'karbohidrat' => 45, 'lemak' => 18, 'gambar' => 'https://awsimages.detik.net.id/community/media/visual/2022/02/28/resep-tuna-melt-sandwich_43.jpeg?w=1200'],
            ['nama_menu' => 'Roti Gandum & Sop Jamur', 'deskripsi' => 'Dua lembar roti gandum utuh dengan semangkuk besar sop jamur krim rendah lemak.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 490, 'protein' => 20, 'karbohidrat' => 55, 'lemak' => 20, 'gambar' => 'https://img-global.cpcdn.com/recipes/2d2d5ccc315ab76e/200x200f0.5_0.517966_1.0q80/champignon-mushroom-cream-soup-foto-resep-utama.jpg'],
            ['nama_menu' => 'Nasi Putih & Tumis Cumi', 'deskripsi' => 'Nasi putih dengan tumis cumi asin cabe hijau dan kangkung.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 470, 'protein' => 28, 'karbohidrat' => 55, 'lemak' => 16, 'gambar' => 'https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/e228da28-d5b9-43a3-85d3-cd473aec8801_Go-Biz_20210309_104532.jpeg?auto=format'],
            ['nama_menu' => 'Pecel Madiun Nasi Putih', 'deskripsi' => 'Pecel sayur komplit dengan nasi putih dan tahu/tempe.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 520, 'protein' => 20, 'karbohidrat' => 60, 'lemak' => 22, 'gambar' => 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/268/2023/09/29/Nasi-Pecel-Madiun-merupakan-makanan-khas-Kota-Madiun-masakapahariinicom-808062729.jpg'],
            ['nama_menu' => 'Burger Vegan Patty Tahu', 'deskripsi' => 'Roti burger gandum dengan patty tahu, selada, dan saus BBQ ringan.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 450, 'protein' => 20, 'karbohidrat' => 55, 'lemak' => 18, 'gambar' => 'https://imgx.parapuan.co/crop/0x0:0x0/x/photo/2021/05/06/vegan-tofu-veggie-burgers-recipe-20210506100318.jpg'],
            ['nama_menu' => 'Chicken Katsu Curry', 'deskripsi' => 'Nasi putih dengan potongan dada ayam Katsu panggang (non-goreng) dan saus kari Jepang encer.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 530, 'protein' => 35, 'karbohidrat' => 60, 'lemak' => 18, 'gambar' => 'https://img-global.cpcdn.com/recipes/59929bc5c150b7b1/680x781cq80/53-rice-bowl-chicken-katsu-curry-foto-resep-utama.jpg'],
            ['nama_menu' => 'Quinoa Bowl Tuna Mayo', 'deskripsi' => 'Quinoa dengan tuna in water dan mayones rendah lemak, sayuran.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 530, 'protein' => 30, 'karbohidrat' => 55, 'lemak' => 22, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB-iTUH5DEAJMAmNkTjtdKi5VhtTgoTo_-hg&s'],
            ['nama_menu' => 'Sup Krim Jagung Ayam', 'deskripsi' => 'Semangkuk sup krim jagung dengan suwiran ayam, disajikan dengan garlic bread gandum.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 25, 'karbohidrat' => 45, 'lemak' => 22, 'gambar' => 'https://assets-cloudflare.segari-ops.id/recipes/sup-krim-jagung-lsbc3y7bKHG9T.jpg'],
            ['nama_menu' => 'Nasi Daun Jeruk Ayam', 'deskripsi' => 'Nasi putih daun jeruk dengan tumisan dada ayam dan buncis.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 460, 'protein' => 30, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/1067/2024/11/05/Screenshot_20241104-202017_Chrome-43047995.jpg'],
            ['nama_menu' => 'Salad Sayur & Beef Patty', 'deskripsi' => 'Salad sayuran segar dengan beef patty panggang dan dressing balsamic.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 470, 'protein' => 35, 'karbohidrat' => 30, 'lemak' => 25, 'gambar' => 'https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/0d1ee3a9-04ca-41f4-b265-8ef1451d3024_Go-Food-Merchant_20251013_112342.jpeg'],
        ];

        // ==========================================
        // 3. WEIGHT LOSS SIANG (30 ITEM)
        // ==========================================
        $weightloss_siang = [
            ['nama_menu' => 'Salad Wrap Ayam Panggang', 'deskripsi' => 'Tortilla gandum isi dada ayam panggang, selada segar, dan dressing rendah lemak.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 320, 'protein' => 25, 'karbohidrat' => 30, 'lemak' => 8, 'gambar' => 'https://www.chilesandsmoke.com/wp-content/uploads/2025/06/Grilled-Chicken-Wraps_002b-819x1024.jpg'],
            ['nama_menu' => 'Sup Tomat', 'deskripsi' => 'Sup tomat kaya serat dengan fresh basil dan low-fat cream, disajikan dengan potongan ayam.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 350, 'protein' => 25, 'karbohidrat' => 35, 'lemak' => 12, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrNPagqGJNyYr_2oPB9O_CLtAyM1CCzilZ9Q&s'],
            ['nama_menu' => 'Sayur Bening Tahu', 'deskripsi' => 'Sayur bening bayam dan jagung, disajikan dengan tahu rebus 2 potong.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 290, 'protein' => 15, 'karbohidrat' => 35, 'lemak' => 9, 'gambar' => 'https://cdn0-production-images-kly.akamaized.net/cnZ3pstIAbanIw8g4GHiY4aJAhg=/0x31:999x594/1200x675/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/4506445/original/077351100_1689673044-shutterstock_2325262535.jpg'],
            ['nama_menu' => 'Omelet Putih Telur Sayur', 'deskripsi' => 'Omelet dari 4 putih telur dengan jamur dan paprika (tanpa kuning telur).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 250, 'protein' => 20, 'karbohidrat' => 15, 'lemak' => 10, 'gambar' => 'https://beautifuleatsandthings.com/wp-content/uploads/2018/05/Veggie-Stuffed-Egg-White-Omelet.jpg'],
            ['nama_menu' => 'Nasi Shirataki', 'deskripsi' => 'Nasi Shirataki dengan tumis udang kecil dan buncis.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 280, 'protein' => 20, 'karbohidrat' => 20, 'lemak' => 12, 'gambar' => 'https://i0.wp.com/resepkoki.id/wp-content/uploads/2021/03/Resep-Nasi-Goreng-Shirataki.jpg?fit=996%2C1328&ssl=1'],
            ['nama_menu' => 'Chicken Steak & Brokoli', 'deskripsi' => 'Dada ayam panggang 100g (tanpa kulit) dengan brokoli kukus dan sedikit saus jamur.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 310, 'protein' => 30, 'karbohidrat' => 15, 'lemak' => 15, 'gambar' => 'https://media.istockphoto.com/id/1162237157/id/foto/tumis-ayam-chicken-steak-dengan-brokoli.jpg?s=170667a&w=0&k=20&c=gOSDIF5YqWr-oXQFiy1U1wHHPMl5U1m9zNaeJdkgG00='],
            ['nama_menu' => 'Salad Ayam Panggang Lemon', 'deskripsi' => 'Dada ayam panggang 80g, selada, mentimun, dan tomat dengan dressing minyak zaitun dan lemon.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 360, 'protein' => 12, 'karbohidrat' => 30, 'lemak' => 18, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ97ym6eIY312wuLfrQjh0jJmDbGZpoPmtE1Q&s'],
            ['nama_menu' => 'Tumis Sawi Putih & Ayam Cincang', 'deskripsi' => 'Tumis sawi putih dan ayam cincang rendah minyak, disajikan tanpa nasi.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 300, 'protein' => 28, 'karbohidrat' => 15, 'lemak' => 14, 'gambar' => 'https://awsimages.detik.net.id/community/media/visual/2022/07/24/resep-sawi-putih-tumis-ayam_43.jpeg?w=650'],
            ['nama_menu' => 'Sandwich Tuna Gandum', 'deskripsi' => 'Dua lembar roti gandum utuh dengan tuna in water dan selada.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 330, 'protein' => 25, 'karbohidrat' => 30, 'lemak' => 10, 'gambar' => 'https://cdn0-production-images-kly.akamaized.net/cPImde3PApSSMMv6gHEBIz-ujpA=/0x0:7952x4482/469x260/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/3644725/original/082558000_1637895563-shutterstock_1369751798.jpg'],
            ['nama_menu' => 'Sup Jagung Ayam Bening', 'deskripsi' => 'Semangkuk sup jagung dan ayam (dada) kuah bening, sangat ringan.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 250, 'protein' => 20, 'karbohidrat' => 25, 'lemak' => 8, 'gambar' => 'https://i0.wp.com/resepkoki.id/wp-content/uploads/2019/04/Resep-sup-jagung.jpg?fit=1920%2C1920&ssl=1'],
            ['nama_menu' => 'Lentil Soup & Roti Gandum', 'deskripsi' => 'Semangkuk sup lentil kaya serat, disajikan dengan 1 lembar roti gandum.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 360, 'protein' => 18, 'karbohidrat' => 45, 'lemak' => 10, 'gambar' => 'https://png.pngtree.com/png-vector/20250903/ourlarge/pngtree-hearty-lentil-soup-with-vegetables-and-herbs-served-with-whole-wheat-png-image_17358577.webp'],
            ['nama_menu' => 'Ubi Jalar & Edamame Kukus', 'deskripsi' => 'Ubi jalar rebus/kukus (120g) dengan semangkuk kecil edamame kukus (tinggi serat dan protein nabati).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 310, 'protein' => 15, 'karbohidrat' => 50, 'lemak' => 6, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS53DLz8lebhdm7C_BDgUn_plpvDcl4VEq7GQ&s'],
            ['nama_menu' => 'Tofu Scramble & Sayur', 'deskripsi' => 'Tahu yang dihancurkan dan ditumis seperti orak-arik telur, dengan sayuran.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 320, 'protein' => 18, 'karbohidrat' => 25, 'lemak' => 16, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR6bPC_mF5cdxn9BmEZnn4ihLC0axGQEzZ3Q&s'],
            ['nama_menu' => 'Pasta Gandum Aglio Olio', 'deskripsi' => 'Pasta gandum utuh (50g kering) dengan sedikit minyak zaitun, bawang putih, dan cabai.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 350, 'protein' => 12, 'karbohidrat' => 50, 'lemak' => 12, 'gambar' => 'https://img-global.cpcdn.com/recipes/082f52aaa417a199/680x781f0.5_0.524869_1.0q80/creamy-spaghetti-gandum-tanpa-minyakdiet-clean-eat-foto-resep-utama.jpg'],
            ['nama_menu' => 'Wrap Sayur Tahu Pedas', 'deskripsi' => 'Tortilla gandum diisi aneka sayuran dan tahu pedas panggang.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 340, 'protein' => 15, 'karbohidrat' => 40, 'lemak' => 14, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFNuwrc91zFnI4vR2jSwXbar3dWczr5TDFFA&s'],
            ['nama_menu' => 'Bubur Oatmeal Ayam', 'deskripsi' => 'Bubur yang terbuat dari oatmeal asin, disajikan dengan suwiran ayam rebus.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 300, 'protein' => 20, 'karbohidrat' => 40, 'lemak' => 8, 'gambar' => 'https://www.dapurkobe.co.id/wp-content/uploads/bubur-ayam-oatmeal.jpg'],
            ['nama_menu' => 'Salad Udang Jeruk', 'deskripsi' => 'Salad hijau dengan udang rebus (70g) dan dressing jeruk ringan.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 310, 'protein' => 25, 'karbohidrat' => 20, 'lemak' => 15, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL3oIyRvBU5XublIBQpxjDFtgHCuQkjH-fKw&s'],
            ['nama_menu' => 'Ubi Jalar Rebus & Dada Ayam', 'deskripsi' => 'Ubi jalar rebus (150g) sebagai sumber karbohidrat, disajikan dengan dada ayam kukus (100g).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 410, 'protein' => 35, 'karbohidrat' => 45, 'lemak' => 10, 'gambar' => 'https://media.istockphoto.com/id/1216956755/id/foto/dada-ayam-panggang-kurus-dan-sayuran-ubi-jalar-panggang-brokoli-rebus.jpg?s=170667a&w=0&k=20&c=ImKhGHq2VXKoMmUl2ndQ2JMX7UeszUO_0vGrpinw7kQ='],
            ['nama_menu' => 'Sup Ikan Salmon', 'deskripsi' => 'Sup bening dengan potongan salmon, jahe, dan sayuran.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 360, 'protein' => 30, 'karbohidrat' => 15, 'lemak' => 20, 'gambar' => 'https://asset.kompas.com/crops/P-FszAphSvChw8d2_I0QPohYQrw=/104x0:972x579/1200x800/data/photo/2022/01/29/61f51c59d7587.jpg'],
            ['nama_menu' => 'Tumis Brokoli dan Jamur', 'deskripsi' => 'Tumis brokoli dan jamur, disajikan dengan 1 potong dada ayam kukus.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 330, 'protein' => 32, 'karbohidrat' => 18, 'lemak' => 10, 'gambar' => 'https://asset.kompas.com/crops/Wucz8TUI4gvKqmfJt1weHZPckyU=/52x38:932x625/1200x800/data/photo/2023/01/16/63c565abb76bb.jpg'],
            ['nama_menu' => 'Pecel Sayur Porsi Kecil', 'deskripsi' => 'Pecel sayuran rebus porsi kecil dengan tempe kukus.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 300, 'protein' => 10, 'karbohidrat' => 35, 'lemak' => 14, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-h0uyRCcbzwXHn92gGc57q5JI9xcZkGe77w&s'],
            ['nama_menu' => 'Kentang Rebus & Daging', 'deskripsi' => '150g kentang rebus dengan irisan daging sapi panggang (80g).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 400, 'protein' => 35, 'karbohidrat' => 40, 'lemak' => 12, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT7cmLQotWvWlT5R1Z7Igd_rSxRpIqUbtq8g&s'],
            ['nama_menu' => 'Soto Ayam Kecil', 'deskripsi' => 'Semangkuk besar soto ayam (kuah bening) tanpa nasi dan tanpa perkedel.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 280, 'protein' => 30, 'karbohidrat' => 15, 'lemak' => 10, 'gambar' => 'https://cdn0-production-images-kly.akamaized.net/E_AYIEYV7h5rU_4XdXUNsY66sWQ=/0x266:6000x3648/500x281/filters:quality(75):strip_icc()/kly-media-production/medias/4917530/original/059469900_1723604105-close-up-high-protein-soup-meal__1_.jpg'],
            ['nama_menu' => 'Wrap Falafel Vegan', 'deskripsi' => 'Tortilla gandum berisi falafel (kacang Arab/protein nabati) panggang, dan sayuran mediterranean.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 390, 'protein' => 20, 'karbohidrat' => 50, 'lemak' => 14, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa5iH26ubcQ1jwL8QMyiVcMLxCnp0ABq58mQ&s'],
            ['nama_menu' => 'Tacos Ikan Panggang', 'deskripsi' => 'Dua buah tacos jagung dengan isian ikan tilapia panggang dan salsa.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 390, 'protein' => 30, 'karbohidrat' => 35, 'lemak' => 14, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnU3I0qWd4Rong0YUxEvKUKQXGw_c1L-eHvg&s'],
            ['nama_menu' => 'Lodeh Tahu Tempe Kecil', 'deskripsi' => 'Sayur lodeh tahu tempe (santan encer) dengan nasi merah (100g).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 420, 'protein' => 18, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://img-global.cpcdn.com/recipes/b25a6d3cb2f295cf/680x781cq80/lodeh-tahu-tempe-kacang-panjang-foto-resep-utama.jpg'],
            ['nama_menu' => 'Sop Ikan Bening Kakap', 'deskripsi' => 'Sop bening berisi fillet ikan kakap (80g) dengan potongan sayuran dan tomat hijau.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 330, 'protein' => 30, 'karbohidrat' => 15, 'lemak' => 16, 'gambar' => 'https://asset.kompas.com/crops/6Sg43b-WTcSyhYa0VJNJ_5pg_bc=/0x0:1000x667/1200x800/data/photo/2022/08/03/62e9c0cb8f53f.jpeg'],
            ['nama_menu' => 'Sandwich Ayam Basil', 'deskripsi' => 'Roti gandum dengan dada ayam panggang, tomat, dan daun basil segar.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 340, 'protein' => 30, 'karbohidrat' => 30, 'lemak' => 10, 'gambar' => 'https://potatorolls.com/wp-content/uploads/Lemon-Basil-Grilled-Chicken3.jpg'],
            ['nama_menu' => 'Mie Shirataki Kuah', 'deskripsi' => 'Mie shirataki dengan kuah kaldu sayur bening, isian telur dan sayur.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 260, 'protein' => 15, 'karbohidrat' => 25, 'lemak' => 10, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDtwRqW-e91Z3zfd4a9xU0fRCYc8VIs_2njg&s'],
            ['nama_menu' => 'Sayur Asem & Telur Rebus', 'deskripsi' => 'Semangkuk sayur asem bening dengan 2 telur rebus.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 350, 'protein' => 15, 'karbohidrat' => 40, 'lemak' => 15, 'gambar' => 'https://asset.kompas.com/crops/l2w0uVRiyp9x_PMz2R9K_NVO5IU=/106x75:906x608/1200x800/data/photo/2022/05/07/627600fb60dc3.jpg'],
        ];

        // ==========================================
        // 4. BULKING SIANG (30 ITEM)
        // ==========================================
        $bulking_siang = [
            ['nama_menu' => 'Power Beef Bowl Extra', 'deskripsi' => 'Nasi merah, daging sapi lada hitam, telur rebus, dan brokoli.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 750, 'protein' => 50, 'karbohidrat' => 85, 'lemak' => 30, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNOgSWA00mBalV_mCBJZUJurT_ZjV6SVrDpw&s'],
            ['nama_menu' => 'Nasi Kari Ayam Kental', 'deskripsi' => 'Nasi putih dengan kari ayam santan kental dan potongan kentang.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 880, 'protein' => 45, 'karbohidrat' => 90, 'lemak' => 45, 'gambar' => 'https://www.finnafood.com/blog/wp-content/uploads/2024/07/resep-kari-ayam-2.jpg'],
            ['nama_menu' => 'Lasagna Daging Sapi', 'deskripsi' => 'Sepotong besar lasagna berlapis dengan keju mozzarella dan saus béchamel krim.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 900, 'protein' => 50, 'karbohidrat' => 75, 'lemak' => 50, 'gambar' => 'https://d12man5gwydfvl.cloudfront.net/wp-content/uploads/2017/06/Mau-Bisa-Bikin-Lasagna-Ini-Dia-Resep-Lasagna-Sederhana-Yang-Enak-Banget-dan-Bikin-Kamu-Ketagihan-Masak-Dirumah-940x667.jpg'],
            ['nama_menu' => 'Nasi Goreng Kambing', 'deskripsi' => 'Nasi goreng porsi jumbo dengan daging kambing, telur, dan minyak banyak.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 900, 'protein' => 45, 'karbohidrat' => 95, 'lemak' => 48, 'gambar' => 'https://awsimages.detik.net.id/community/media/visual/2024/06/17/resep-nasi-goreng-kambing_43.jpeg?w=600&q=90'],
            ['nama_menu' => 'Nasi Campur Rendang', 'deskripsi' => 'Nasi putih dengan rendang daging porsi besar dan gulai nangka.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 820, 'protein' => 40, 'karbohidrat' => 85, 'lemak' => 40, 'gambar' => 'https://nibble-images.b-cdn.net/nibble/original_images/nasi-campur-enak-di-sunter-05.jpg?class=large'],
            ['nama_menu' => 'Burrito Bowl Daging Ganda', 'deskripsi' => 'Nasi, daging sapi cincang, keju, kacang hitam, sour cream, dan guacamole.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 790, 'protein' => 50, 'karbohidrat' => 75, 'lemak' => 38, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsXreY3dxbOXk-Zx9IrSJGh_M-pXH9BZ-i8g&s'],
            ['nama_menu' => 'Steak Sapi & Kentang Keju', 'deskripsi' => 'Steak T-Bone dengan kentang tumbuk keju dan saus jamur.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 950, 'protein' => 60, 'karbohidrat' => 70, 'lemak' => 55, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy1pKzyHms0MynNZ8VwgIvJAWeQkv-M-V_OA&s'],
            ['nama_menu' => 'Nasi Bakar Udang Komplit', 'deskripsi' => 'Nasi dibakar dengan isian udang, cumi, dan santan.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 760, 'protein' => 35, 'karbohidrat' => 80, 'lemak' => 38, 'gambar' => 'https://asset.kompas.com/crops/GXwCjiQKaChTXZd73SgeU_j3ZcM=/0x381:800x914/1200x800/data/photo/2022/06/05/629c1ffc9ce3d.jpeg'],
            ['nama_menu' => 'Ayam Geprek Keju Mozarella', 'deskripsi' => 'Nasi putih dengan ayam geprek renyah, keju mozarella leleh, dan sambal.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 880, 'protein' => 45, 'karbohidrat' => 75, 'lemak' => 48, 'gambar' => 'https://o-cdf.oramiland.com/unsafe/cnc-magazine.oramiland.com/parenting/original_images/ayam_geprek_mozarella_SrANBxa.png'],
            ['nama_menu' => 'Power Bowl Salmon Teriyaki', 'deskripsi' => 'Nasi putih, fillet salmon panggang dengan saus teriyaki kental, dan alpukat.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 790, 'protein' => 45, 'karbohidrat' => 75, 'lemak' => 38, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMxxcBy802yOhehdpACwj66w93M9RgR7_J_Q&s'],
            ['nama_menu' => 'Creamy Mac and Cheese Jumbo', 'deskripsi' => 'Macaroni dan keju cheddar serta mozzarella melimpah dengan topping daging asap/sapi.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 820, 'protein' => 40, 'karbohidrat' => 70, 'lemak' => 45, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaK_Xkk__UWUtPYVwJSRmlXbFFEmrxRd0A2Q&s'],
            ['nama_menu' => 'Kwetiau Goreng Seafood', 'deskripsi' => 'Kwetiau porsi besar digoreng dengan minyak, isian cumi, udang, dan bakso.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 800, 'protein' => 35, 'karbohidrat' => 90, 'lemak' => 35, 'gambar' => 'https://dcostseafood.id/wp-content/uploads/2024/06/Kwetiau-goreng-seafood.jpg'],
            ['nama_menu' => 'Nasi Putih & Sapi Lada Hitam', 'deskripsi' => 'Nasi putih (150g) dengan irisan daging sapi lada hitam (rendah minyak/kecap) dan paprika.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 500, 'protein' => 30, 'karbohidrat' => 60, 'lemak' => 18, 'gambar' => 'https://www.unileverfoodsolutions.co.id/dam/ufs-id/recipes/Beef%20Blackpepper%20RIce.jpg'],
            ['nama_menu' => 'Pizza Slice (2 Potong) Daging', 'deskripsi' => 'Dua potong pizza dengan topping daging (pepperoni/sapi) dan keju ekstra.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 700, 'protein' => 35, 'karbohidrat' => 70, 'lemak' => 35, 'gambar' => 'https://png.pngtree.com/thumb_back/fw800/background/20230325/pngtree-pizza-with-cheddar-cheese-and-minced-beef-meal-meat-pizzeria-photo-image_51081874.jpg'],
            ['nama_menu' => 'Nasi Campur Bali Babi', 'deskripsi' => 'Nasi dengan lauk non-vegan lengkap (sate lilit, samcan, urutan, dll.).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 920, 'protein' => 50, 'karbohidrat' => 80, 'lemak' => 48, 'gambar' => 'https://www.shutterstock.com/image-photo/nasi-campur-babi-guling-balinese-260nw-782704750.jpg'],
            ['nama_menu' => 'Ayam Pop Sambal & Nasi', 'deskripsi' => 'Nasi putih (250g) dengan dua potong ayam pop (lemak sedang) dan sambal.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 730, 'protein' => 40, 'karbohidrat' => 80, 'lemak' => 30, 'gambar' => 'https://static.promediateknologi.id/crop/57x786:1039x1913/0x0/webp/photo/p2/74/2025/04/15/Screenshot_20250415_070341-4234789149.jpg'],
            ['nama_menu' => 'Tahu Telur Petis Lontong', 'deskripsi' => 'Tahu telur petis dengan lontong, bumbu kacang kental, dan porsi kerupuk melimpah.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 750, 'protein' => 30, 'karbohidrat' => 85, 'lemak' => 35, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeKNuqujI06vUAnZpLuP1x_cYSBQfIc3qYpQ&s'],
            ['nama_menu' => 'Nasi Putih & Semur Daging', 'deskripsi' => 'Nasi putih (200g) dengan semur daging sapi porsi besar, telur, dan kuah kental.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 780, 'protein' => 45, 'karbohidrat' => 75, 'lemak' => 35, 'gambar' => 'https://i.pinimg.com/736x/de/0e/4d/de0e4d6ea001aeaf8388cffe2734eca7.jpg'],
            ['nama_menu' => 'Bubur Ayam Komplit JUMBO', 'deskripsi' => 'Bubur ayam porsi besar dengan kerupuk, kacang, cakwe, dan sate-satean.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 690, 'protein' => 35, 'karbohidrat' => 80, 'lemak' => 28, 'gambar' => 'https://awsimages.detik.net.id/community/media/visual/2018/05/07/613c9fdf-fef7-4a56-8995-bd3a494a2bc6.jpeg?w=600&q=90'],
            ['nama_menu' => 'Nasi Bakar Keju Mozarella', 'deskripsi' => 'Nasi dibakar dengan keju mozarella, isian ayam suwir, porsi lemak tinggi.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 720, 'protein' => 35, 'karbohidrat' => 70, 'lemak' => 35, 'gambar' => 'https://awsimages.detik.net.id/community/media/visual/2022/03/02/instagrammomuraid.jpeg?w=1200'],
            ['nama_menu' => 'Nasi Putih & Empal Daging', 'deskripsi' => 'Nasi putih (200g) dengan empal daging sapi goreng tebal dan sambal.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 750, 'protein' => 50, 'karbohidrat' => 75, 'lemak' => 35, 'gambar' => 'https://lapispahlawan.co.id/uploads/6/2023-11/nasi_empal.jpg'],
            ['nama_menu' => 'Power Bowl Vegan Extra', 'deskripsi' => 'Nasi merah (200g), kacang-kacangan, tahu dan tempe goreng, alpukat (lemak sehat).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 680, 'protein' => 30, 'karbohidrat' => 80, 'lemak' => 28, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeIHu5udNKz71iMt2d0Yo-3kcaOH3Nn9tgZg&s'],
            ['nama_menu' => 'Fish and Chips Porsi Jumbo', 'deskripsi' => 'Fillet ikan goreng tepung porsi besar dengan tartar sauce, disajikan dengan kentang goreng melimpah.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 900, 'protein' => 45, 'karbohidrat' => 80, 'lemak' => 50, 'gambar' => 'https://realfood.tesco.com/recipes/smoked-salmon-and-rye-bread-with-pickled-radishes-and-cucumber.html'],
            ['nama_menu' => 'Salad Sayur & Tuna Panggang', 'deskripsi' => 'Salad sayuran lengkap (dengan biji-bijian) dan fillet tuna panggang (100g) tanpa dressing berat.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 420, 'protein' => 35, 'karbohidrat' => 30, 'lemak' => 18, 'gambar' => 'https://img-global.cpcdn.com/recipes/e197218d3c9554a4/680x781cq80/tuna-fresh-salad-foto-resep-utama.jpg'],
            ['nama_menu' => 'Nasi Ayam Mentega', 'deskripsi' => 'Nasi putih (200g) dengan tumis ayam saus mentega (porsi saus besar).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 810, 'protein' => 40, 'karbohidrat' => 85, 'lemak' => 38, 'gambar' => 'https://dcostseafood.id/wp-content/uploads/2021/12/Nasi-ayam-fillet-mentega-600x600.jpg'],
            ['nama_menu' => 'Sayur Bening Bayam & Jagung', 'deskripsi' => 'Semangkuk besar sayur bayam bening dengan irisan jagung manis, disajikan dengan 2 potong ikan kukus/panggang.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 390, 'protein' => 30, 'karbohidrat' => 45, 'lemak' => 10, 'gambar' => 'https://assets-cloudflare.segari-ops.id/recipes/sayur-bening-bayam-lsbc8j6kVPQ1Z.jpg'],
            ['nama_menu' => 'Nasi Bistik Sapi Komplit', 'deskripsi' => 'Nasi putih (200g) dengan bistik daging sapi porsi besar, telur, dan kentang goreng.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 850, 'protein' => 45, 'karbohidrat' => 80, 'lemak' => 40, 'gambar' => 'https://dcostseafood.id/wp-content/uploads/2021/12/Nasi-bistik-sapi-mentega.jpg'],
            ['nama_menu' => 'Fettuccine Alfredo Udang', 'deskripsi' => 'Pasta fettuccine dengan saus alfredo creamy dan topping udang, porsi besar.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 800, 'protein' => 35, 'karbohidrat' => 70, 'lemak' => 45, 'gambar' => 'https://www.budgetbytes.com/wp-content/uploads/2022/01/Shrimp-Alfredo-Pasta-bowl2.jpg'],
            ['nama_menu' => 'Sup Buntut Sapi Kuah Santan', 'deskripsi' => 'Semangkuk besar sup buntut sapi kuah santan dengan nasi putih (150g).', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 800, 'protein' => 45, 'karbohidrat' => 70, 'lemak' => 40, 'gambar' => 'https://www.unileverfoodsolutions.co.id/dam/global-ufs/mcos/SEA/calcmenu/recipes/ID-recipes/red-meats-&-red-meat-dishes/oxtail-soup/main-header.jpg'],
            ['nama_menu' => 'Nasi Putih & Cumi Telur Asin', 'deskripsi' => 'Nasi putih (200g) dengan tumis cumi telur asin yang berminyak dan gurih.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 830, 'protein' => 40, 'karbohidrat' => 75, 'lemak' => 45, 'gambar' => 'https://i0.wp.com/resepkoki.id/wp-content/uploads/2018/02/Resep-Cumi-telur-asin.jpg?fit=500%2C479&ssl=1'],
        ];

          // ==========================================
        // 7. BULKING MALAM (30 ITEM)
        // ==========================================
        $bulking_malam = [
            ['nama_menu' => 'Beef Blackpepper', 'deskripsi' => 'Tumis daging sapi lada hitam dan minyak zaitun.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 780, 'protein' => 50, 'karbohidrat' => 85, 'lemak' => 30, 'gambar' => 'https://images.pexels.com/photos/1251208/pexels-photo-1251208.jpeg'],
            ['nama_menu' => 'Pasta Creamy Bolognese', 'deskripsi' => 'Pasta dengan saus krim daging sapi cincang, dan keju parmesan (porsi besar).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 850, 'protein' => 45, 'karbohidrat' => 80, 'lemak' => 45, 'gambar' => 'https://images.pexels.com/photos/2773940/pexels-photo-2773940.jpeg'],
            ['nama_menu' => 'Nasi Uduk Ayam Goreng', 'deskripsi' => 'Nasi uduk gurih dengan paha ayam goreng (berkulit) dan sambal terasi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 810, 'protein' => 40, 'karbohidrat' => 85, 'lemak' => 40, 'gambar' => 'https://www.dapurkobe.co.id/wp-content/uploads/nasi-uduk-ayam-crispy.jpg'],
            ['nama_menu' => 'Soto Betawi Daging Santan Nasi', 'deskripsi' => 'Semangkuk soto Betawi kuah santan kental dengan daging sapi, disajikan dengan nasi (150g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 880, 'protein' => 45, 'karbohidrat' => 70, 'lemak' => 55, 'gambar' => 'https://asset.kompas.com/crops/a5LYD_3KtzA7sB62uAFMhx7Vfjg=/0x0:1000x667/1200x800/data/photo/2023/07/03/64a24c69d154d.jpg'],
            ['nama_menu' => 'Nasi Campur Daging Sapi & Telur', 'deskripsi' => 'Nasi putih dengan daging sapi empal, telur balado, dan sayur bersantan.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 780, 'protein' => 40, 'karbohidrat' => 80, 'lemak' => 35, 'gambar' => 'https://images.pexels.com/photos/8498870/pexels-photo-8498870.jpeg'],
            ['nama_menu' => 'Nasi Goreng Seafood', 'deskripsi' => 'Nasi goreng porsi besar dengan udang, cumi, telur, dan minyak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 800, 'protein' => 35, 'karbohidrat' => 90, 'lemak' => 38, 'gambar' => 'https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/303/2024/03/02/WhatsApp-Image-2021-07-09-at-51446-PM-1-374542852.jpeg'],
            ['nama_menu' => 'Double Cheese Burger & Kentang', 'deskripsi' => 'Dua beef patty dengan keju full-fat, dibungkus tortilla besar, dengan kentang rebus/panggang 150g.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 920, 'protein' => 55, 'karbohidrat' => 60, 'lemak' => 55, 'gambar' => 'https://images.pexels.com/photos/3738755/pexels-photo-3738755.jpeg'],
            ['nama_menu' => 'Vegan Tempeh Burrito Bowl', 'deskripsi' => 'Burrito bowl nasi merah dengan tempeh, kacang hitam, jagung, alpukat & sayuran — tinggi kalori & protein, cocok bulking.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 780, 'protein' => 35, 'karbohidrat' => 90, 'lemak' => 32, 'gambar' => 'https://forkfulofplants.com/wp-content/uploads/2021/09/Tofu-Buddha-Bowl-030.jpg'],
            ['nama_menu' => 'Gulai Ayam Paha Bawah Nasi', 'deskripsi' => 'Nasi putih dengan paha ayam bawah (2 potong) bumbu gulai kental.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 750, 'protein' => 40, 'karbohidrat' => 70, 'lemak' => 38, 'gambar' => 'https://cdn0-production-images-kly.akamaized.net/msy8OctlAp0x0F83cSb8558rSU4=/1x16:1000x579/469x260/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/3386754/original/012310700_1614242493-shutterstock_1688670580.jpg'],
            ['nama_menu' => 'Nasi Siram Komplit', 'deskripsi' => 'Nasi putih disiram kuah kental berisi daging sapi, udang, dan telur porsi besar.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 790, 'protein' => 40, 'karbohidrat' => 85, 'lemak' => 35, 'gambar' => 'https://img-global.cpcdn.com/recipes/291c7a64d83cebbd/680x781f0.5_0.56875_1.0q80/nasi-siram-udang-foto-resep-utama.jpg'],
            ['nama_menu' => 'Nasi Ayam Goreng Balado', 'deskripsi' => 'Nasi dengan ayam goreng balado.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 700, 'protein' => 40, 'karbohidrat' => 75, 'lemak' => 30, 'gambar' => 'https://img.freepik.com/foto-premium/nasi-ayam-geprek-adalah-makanan-indonesia-ayam-goreng-renyah-dengan-sambal-bawang-pedas-disajikan-dengan-nasi_464898-6628.jpg'],
            ['nama_menu' => 'High-Protein Tempeh Rice Bowl', 'deskripsi' => 'Bowl nasi putih/merah dengan tempeh panggang, brokoli, wortel & quinoa — lengkap karbo + protein nabati tinggi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 820, 'protein' => 38, 'karbohidrat' => 95, 'lemak' => 30, 'gambar' => 'https://klaraslife.com/wp-content/uploads/2020/01/IMG_1944-1.jpg'],
            ['nama_menu' => 'Nasi Putih & Tumis Cumi Asin', 'deskripsi' => 'Nasi putih dengan tumis cumi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 810, 'protein' => 40, 'karbohidrat' => 85, 'lemak' => 38, 'gambar' => 'https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/e228da28-d5b9-43a3-85d3-cd473aec8801_Go-Biz_20210309_104532.jpeg?auto=format'],
            ['nama_menu' => 'Sup Krim Ayam & Roti Bawang', 'deskripsi' => 'Semangkuk besar sup krim ayam kental, disajikan dengan 2 potong roti bawang putih.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 680, 'protein' => 30, 'karbohidrat' => 60, 'lemak' => 35, 'gambar' => 'https://www.orchidsandsweettea.com/wp-content/uploads/2023/09/Garlic-Soup-9.jpg'],
            ['nama_menu' => 'Nasi Putih & Daging Sapi Lada Hitam', 'deskripsi' => 'Nasi putih dengan tumis daging sapi lada hitam.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 790, 'protein' => 45, 'karbohidrat' => 85, 'lemak' => 32, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpmldxGHwoPkxCzdC-iAy8v_gdSDzSKmJq3w&s'],
            ['nama_menu' => 'Martabak Telur Sayuran', 'deskripsi' => 'Dua potong martabak telur daging sapi dengan isian sayuran (tinggi lemak dan karbohidrat).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 820, 'protein' => 40, 'karbohidrat' => 70, 'lemak' => 48, 'gambar' => 'https://assets.unileversolutions.com/recipes-v2/257949.jpg'],
            ['nama_menu' => 'Nasi Bakar Salmon', 'deskripsi' => 'Nasi dibakar (porsi besar) dengan isian salmon dan santan/mentega.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 750, 'protein' => 40, 'karbohidrat' => 75, 'lemak' => 35, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKu4TXKOwEE2tQWb7qzZ_1SkX0T2fcCm0BPA&s'],
            ['nama_menu' => 'Nasi Campur Jawa Komplit', 'deskripsi' => 'Nasi dengan lauk ayam bumbu rujak, sate lilit, serundeng, dan sambal.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 730, 'protein' => 40, 'karbohidrat' => 75, 'lemak' => 35, 'gambar' => 'https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-content/uploads/2023/07/18094457/3-Resep-Nasi-Rames-Lezat-Komplet-dengan-Lauknya.jpg'],
            ['nama_menu' => 'High-Protein Chickpea Tempeh Bowl', 'deskripsi' => 'Bowl vegan dengan tempeh, chickpeas, ubi panggang, quinoa & sayur, kaya kalori & protein nabati.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 900, 'protein' => 40, 'karbohidrat' => 100, 'lemak' => 34, 'gambar' => 'https://cookwithcandy.com/wp-content/uploads/2020/10/High-Protein-Vegan-Bowl-1-1351x1351.jpg'],
            ['nama_menu' => 'Nasi Putih & Empal Gepuk', 'deskripsi' => 'Nasi putih dengan 2 potong empal gepuk daging sapi yang berminyak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 820, 'protein' => 50, 'karbohidrat' => 80, 'lemak' => 40, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlKjNTob-8SHFFF3QaPTscepeZRH0kIDbKDw&s'],
            ['nama_menu' => 'Pasta Pesto Krim Keju', 'deskripsi' => 'Pasta dengan saus pesto basil krim kental dan keju.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 760, 'protein' => 30, 'karbohidrat' => 70, 'lemak' => 40, 'gambar' => 'https://img-global.cpcdn.com/recipes/6114bd7be8719156/680x781cq80/pasta-pesto-foto-resep-utama.jpg'],
            ['nama_menu' => 'Vegan Power Bowl Tofu & Nasi', 'deskripsi' => 'Nasi merah dengan porsi besar tahu goreng, tempe, dan kacang-kacangan.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 700, 'protein' => 35, 'karbohidrat' => 85, 'lemak' => 30, 'gambar' => 'https://fullofplants.com/wp-content/uploads/2021/11/comforting-vegan-enchilada-power-bowls-with-spicy-tofu-plant-based-thumb-500x500.jpg'],
            ['nama_menu' => 'Nasi Ayam Kalio Santan', 'deskripsi' => 'Nasi putih dengan paha ayam kalio (kuah santan kental).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 750, 'protein' => 40, 'karbohidrat' => 75, 'lemak' => 38, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1mTLK_hsENS52Q9QcKwZcknwFbHdBIa7bNA&s'],
            ['nama_menu' => 'Lontong Opor Ayam Telur', 'deskripsi' => 'Lontong porsi besar dengan opor ayam (paha) kuah santan kental, dan 2 telur rebus.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 890, 'protein' => 45, 'karbohidrat' => 90, 'lemak' => 45, 'gambar' => 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/catalog-image/112/MTA-179465907/cemilan_keto_low_carb_lontong_opor_ayam_shirataki_keto_debm_full01_d3cvhgsi.jpg'],
            ['nama_menu' => 'Nasi Rawon Daging', 'deskripsi' => 'Semangkuk rawon daging sapi (kuah kental) dengan nasi putih (200g) dan tauge.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 830, 'protein' => 45, 'karbohidrat' => 80, 'lemak' => 40, 'gambar' => 'https://asset.kompas.com/crops/O8v-1M5y8Kj-y7jX_XJ9-9Xj_X4=/0x0:1000x667/750x500/data/photo/2020/03/01/5e5b5b5b5b5b5.jpg'],
            ['nama_menu' => 'Burger Ayam Crispy Jumbo Kentang', 'deskripsi' => 'Burger gandum dengan crispy chicken patty besar, keju, dan kentang panggang (150g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 900, 'protein' => 50, 'karbohidrat' => 75, 'lemak' => 45, 'gambar' => 'https://www.shutterstock.com/image-photo/delicious-burger-crispy-chicken-patty-600nw-2410298835.jpg'],
            ['nama_menu' => 'Nasi Merah & Rendang Tahu Komplit', 'deskripsi' => 'Nasi dengan porsi rendang.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 680, 'protein' => 25, 'karbohidrat' => 70, 'lemak' => 35, 'gambar' => 'https://asset.kompas.com/crops/6ZY7agSGSkw18NVzljnpSh_xfN4=/0x0:1000x667/1200x800/data/photo/2021/05/13/609ce0728a194.jpg'],
            ['nama_menu' => 'Ayam Rica-Rica', 'deskripsi' => 'Ayam rica-rica yang pedas', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 760, 'protein' => 40, 'karbohidrat' => 70, 'lemak' => 38, 'gambar' => 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2022/12/26/3870606096.jpg'],
            ['nama_menu' => 'Chili Con Carne & Nasi', 'deskripsi' => 'Nasi putih dengan semangkuk besar chili con carne (daging, kacang, tomat).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 700, 'protein' => 40, 'karbohidrat' => 70, 'lemak' => 30, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtbqsfdV2cblPyZSkLWdo1mFL2QST5sMTRzg&s'],
            ['nama_menu' => 'Vegan Tofu & Tempeh Power Bowl', 'deskripsi' => 'Rice bowl nasi, tahu goreng, tempe, edamame, sayuran, saus kacang kombinasi yang padat nutrisi untuk bulking.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 850, 'protein' => 42, 'karbohidrat' => 85, 'lemak' => 36, 'gambar' => 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg'],
        ];


        // ==========================================
        // 6. WEIGHT LOSS MALAM (30 ITEM)
        // ==========================================
        $weightloss_malam = [
            ['nama_menu' => 'Sup Ayam Jahe & Sayur', 'deskripsi' => 'Sup bening ayam kampung (dada) dengan wortel, buncis, dan aroma jahe hangat.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 250, 'protein' => 22, 'karbohidrat' => 15, 'lemak' => 8, 'gambar' => 'https://www.dapurkobe.co.id/wp-content/uploads/sop-ayam-bening-jahe.jpg'],
            ['nama_menu' => 'Ikan Tilapia Panggang Lemon', 'deskripsi' => 'Fillet ikan tilapia panggang (100g) dengan irisan lemon dan bayam kukus.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 320, 'protein' => 30, 'karbohidrat' => 10, 'lemak' => 16, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBpSeqpH0-NbAMyKw-D_K-nYTcd7P869kr3g&s'],
            ['nama_menu' => 'Stir Fry Tofu & Sayur Hijau', 'deskripsi' => 'Tahu tinggi protein ditumis dengan brokoli, buncis, dan bayam (minyak zaitun sedikit).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 280, 'protein' => 18, 'karbohidrat' => 20, 'lemak' => 10, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs5KEALZ7miN8c_rvUBuChq3OaHHjCp4T2XQ&s'],
            ['nama_menu' => 'Dada Ayam Kukus & Salad', 'deskripsi' => 'Dada ayam kukus (100g) dengan salad sayuran segar dan dressing balsamic.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 310, 'protein' => 35, 'karbohidrat' => 10, 'lemak' => 15, 'gambar' => 'https://img-global.cpcdn.com/recipes/15e2089de30d77cb/400x400cq80/photo.jpg'],
            ['nama_menu' => 'Nasi Shirataki & Telur', 'deskripsi' => 'Nasi Shirataki dengan 1 butir telur rebus dan tumis kangkung.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 270, 'protein' => 15, 'karbohidrat' => 20, 'lemak' => 12, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxAYI1gaM2JwSmxI9c6lp4LVXbd__6Bw1kzQ&s'],
            ['nama_menu' => 'Sup Wortel dan Kentang Bening', 'deskripsi' => 'Sup bening dengan wortel, kentang (porsi kecil), dan irisan daun bawang.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 200, 'protein' => 5, 'karbohidrat' => 30, 'lemak' => 6, 'gambar' => 'https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-content/uploads/2023/07/31035441/ini-resep-sayur-sop-penuh-nutrisi-yang-jadi-favorit-keluarga.jpg.webp'],
            ['nama_menu' => 'Pecel Sayur Tanpa Karbo', 'deskripsi' => 'Pecel sayuran rebus saja (bayam, kacang panjang), bumbu kacang porsi diet.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 300, 'protein' => 10, 'karbohidrat' => 35, 'lemak' => 14, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgetlSB0_ZI_Su7qeWN9Xw8akGTFdbpCFlfw&s'],
            ['nama_menu' => 'Oatmeal dengan Chia Seeds', 'deskripsi' => 'Oatmeal yang dimasak dengan air/susu skim dan dicampur chia seeds (tanpa gula).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 220, 'protein' => 8, 'karbohidrat' => 35, 'lemak' => 5, 'gambar' => 'https://alexandracooks.com/wp-content/uploads/2022/03/bowlofchiapudding_alexandraskitchen.jpg'],
            ['nama_menu' => 'Tofu Scramble & Paprika', 'deskripsi' => 'Tahu orak-arik (scramble) dengan paprika, tanpa minyak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 240, 'protein' => 15, 'karbohidrat' => 15, 'lemak' => 14, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDfv46ODzy7qZbgWB5BZHWZyLJXLApJHIWvA&s'],
            ['nama_menu' => 'Sup Ikan Dori', 'deskripsi' => 'Sup ikan dori (80g) bening dengan jahe dan sayuran hijau.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 310, 'protein' => 30, 'karbohidrat' => 10, 'lemak' => 15, 'gambar' => 'https://cdn.yummy.co.id/content-images/images/20221017/JqFHgHKhJmyICL1S3cxTzxUQtE3iqp11-31363635393838313035d41d8cd98f00b204e9800998ecf8427e.jpg?x-oss-process=image/resize,w_388,h_388,m_fixed,x-oss-process=image/format,webp'],
            ['nama_menu' => 'Salad Telur Rebus', 'deskripsi' => 'Salad sayuran dengan 2 butir telur rebus (kuningnya 1 saja) dan sedikit dressing.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 290, 'protein' => 18, 'karbohidrat' => 20, 'lemak' => 16, 'gambar' => 'https://cdn.yummy.co.id/content-images/images/20230601/3w918kEZCkQkBZjmA63eu56MoJNtlcmN-31363835363232343039d41d8cd98f00b204e9800998ecf8427e.jpg?x-oss-process=image/resize,w_388,h_388,m_fixed,x-oss-process=image/format,webp'],
            ['nama_menu' => 'Ayam Panggang Madu', 'deskripsi' => 'Dada ayam panggang (70g) dibalut saus madu diet (gula minimal) dan sedikit timun.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 290, 'protein' => 32, 'karbohidrat' => 15, 'lemak' => 11, 'gambar' => 'https://www.hypermart.co.id/wp-content/uploads/elementor/thumbs/41-p5q08igqpoy19f4zhvpgme99ekxgi351gqpgxlozrs.jpg'],
            ['nama_menu' => 'Sup Krim Jamur Rendah Lemak', 'deskripsi' => 'Semangkuk besar sup krim jamur dengan susu rendah lemak (tanpa roti).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 300, 'protein' => 15, 'karbohidrat' => 30, 'lemak' => 12, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvW89uxfDQtE-V6F7luYkMv6Mu468zsxlFMQ&s'],
            ['nama_menu' => 'Tumis Sawi Tofu', 'deskripsi' => 'Tumis sawi putih dan tofu (bumbu minimal) tanpa nasi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 230, 'protein' => 12, 'karbohidrat' => 15, 'lemak' => 14, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfetp2W02u1JRCEbS-xKL4b84QI9opOEAW5g&s'],
            ['nama_menu' => 'Protein Bowl Ikan Tuna', 'deskripsi' => 'Tuna in water (100g) dengan sedikit jagung, dan paprika.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 310, 'protein' => 35, 'karbohidrat' => 20, 'lemak' => 10, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHo2F1QIe0_kekZPrJtGIvnieMilcyv1U8ig&s'],
            ['nama_menu' => 'Bubur Kacang Hijau', 'deskripsi' => 'Bubur kacang hijau tanpa santan dan gula minimal (sebagai pengganti makanan ringan).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 240, 'protein' => 10, 'karbohidrat' => 40, 'lemak' => 4, 'gambar' => 'https://assets-cloudflare.segari-ops.id/recipes/bubur-kacang-hijau-lsbaf7c2pzRNx.jpg'],
            ['nama_menu' => 'Sayur Capcay Bening', 'deskripsi' => 'Capcay kuah bening (brokoli, wortel, sawi) dengan udang kecil (30g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 190, 'protein' => 15, 'karbohidrat' => 20, 'lemak' => 7, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzIJ-6u_u_h4_OD3PP7kryA_zsNmBOYsKzMQ&s'],
            ['nama_menu' => 'Smoothie Protein Hijau', 'deskripsi' => 'Campuran bayam, pisang (kecil), dan bubuk protein vanilla (whey/plant based).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 270, 'protein' => 25, 'karbohidrat' => 25, 'lemak' => 6, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwMcy8SFJao1easL8bFRyZI32UN5yR7tuv-Q&s'],
            ['nama_menu' => 'Poke Bowl Sesame Tofu', 'deskripsi' => 'Tofu panggang balut wijen dengan tumis sawi hijau ringan.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 260, 'protein' => 17, 'karbohidrat' => 18, 'lemak' => 11, 'gambar' => 'https://cdn.veganrecipeclub.org.uk/wp-content/uploads/2022/08/poke-bowl-recipe.jpg'],
            ['nama_menu' => 'Zucchini Bowl Ayam Panggang', 'deskripsi' => 'Sup bening ayam suwir dengan daun ketumbar dan bawang putih, tanpa minyak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 280, 'protein' => 32, 'karbohidrat' => 10, 'lemak' => 12, 'gambar' => 'https://i0.wp.com/poshplate.us/wp-content/uploads/2021/02/Easy-Baked-Chicken-and-Zucchini-Recipe.jpg'],
            ['nama_menu' => 'Salad Alpukat & Edamame', 'deskripsi' => 'Potongan alpukat, edamame rebus, selada, tomat ceri, dressing lemon + sedikit minyak zaitun.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 330, 'protein' => 14, 'karbohidrat' => 18, 'lemak' => 22, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZVY8MWabdzaG84YsPPvC-wdlktoEeVl0VFA&s'],
            ['nama_menu' => 'Kari Ayam Rendah Lemak', 'deskripsi' => 'Kari ayam (50g) dimasak dengan santan rendah lemak dan rempah-rempah (tanpa kentang).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 330, 'protein' => 30, 'karbohidrat' => 10, 'lemak' => 18, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF0uTMfz6c12fpgLJPCBvVyB7fl47_Yu0u-Q&s'],
            ['nama_menu' => 'Soto Ayam', 'deskripsi' => 'Semangkuk soto ayam bening, isian ayam dan sayur.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 280, 'protein' => 30, 'karbohidrat' => 15, 'lemak' => 10, 'gambar' => 'https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480/img/recipe/ras/Assets/23f62312738135ab286e78812093c46b/Derivates/2e373c2ef0bf36c9e8475cbf93347db5a3496309.jpg'],
            ['nama_menu' => 'Telur Dadar Sayur & Keju', 'deskripsi' => '2 butir telur dadar (putihnya saja) dicampur bayam dan sedikit keju mozarella rendah lemak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 250, 'protein' => 20, 'karbohidrat' => 5, 'lemak' => 17, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzt5h5BFUMD5IrJT3axxtU-pCVDz89Gdo28A&s'],
            ['nama_menu' => 'Avocado Toast & Telur Rebus', 'deskripsi' => 'Roti gandum panggang dengan potongan alpukat dan 1 telur rebus, topping sedikit lada hitam.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 280, 'protein' => 12, 'karbohidrat' => 30, 'lemak' => 12, 'gambar' => 'https://cleananddelicious.com/wp-content/uploads/2025/01/avocado-toast.jpg'],
            ['nama_menu' => 'Stir Fry Buncis Sapi', 'deskripsi' => 'Tumis buncis dan irisan tipis daging sapi (60g), tanpa nasi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 340, 'protein' => 25, 'karbohidrat' => 20, 'lemak' => 18, 'gambar' => 'https://delightfulplate.com/wp-content/uploads/2024/08/Vietnamese-Stir-fried-Beef-with-Green-Beans-Bo-Xao-Dau-Que.jpg'],
            ['nama_menu' => 'Sup Sayur Kacang Merah', 'deskripsi' => 'Sup bening dengan kacang merah sebagai sumber karbohidrat dan serat.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 260, 'protein' => 12, 'karbohidrat' => 40, 'lemak' => 4, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRUij6XTvSgYyYmrHVd11YHs2AC-XzD1yW2A&s'],
            ['nama_menu' => 'Salad Greek Feta', 'deskripsi' => 'Salad sayuran dengan keju Feta (rendah lemak) dan sedikit minyak zaitun.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 350, 'protein' => 15, 'karbohidrat' => 25, 'lemak' => 22, 'gambar' => 'https://silkroadrecipes.com/greek-feta-salad/'],
            ['nama_menu' => 'Brokoli Kukus Tuna Mayo', 'deskripsi' => 'Brokoli kukus (porsi besar) dengan 50g tuna kaleng dan sedikit mayones rendah lemak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 280, 'protein' => 28, 'karbohidrat' => 8, 'lemak' => 15, 'gambar' => 'https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2020/12/Broccoli-Tuna-Salad-1-2.jpg'],
            ['nama_menu' => 'Sayur Bening Kentang', 'deskripsi' => 'Sayur bening bayam, disajikan dengan kentang rebus kecil (50g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 260, 'protein' => 7, 'karbohidrat' => 45, 'lemak' => 5, 'gambar' => 'https://assets.unileversolutions.com/v1/961885.jpg'],
        ];

              // ==========================================
        // 5. MAINTAIN MALAM (30 ITEM)
        // ==========================================
        $maintain_malam = [
            ['nama_menu' => 'Ayam Panggang Sayur Kukus', 'deskripsi' => 'Dada ayam panggang dengan ubi jalar dan tumis buncis.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 450, 'protein' => 38, 'karbohidrat' => 35, 'lemak' => 18, 'gambar' => 'https://mealpractice.b-cdn.net/6279028277383168/baked-chicken-and-sweet-potato-with-green-beans-bnmtD4HkTk.webp'],
            ['nama_menu' => 'Sop Daging Sayuran Nasi', 'deskripsi' => 'Semangkuk sup daging sapi dan sayuran, disajikan dengan nasi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 30, 'karbohidrat' => 45, 'lemak' => 20, 'gambar' => 'https://assets.unileversolutions.com/recipes-v2/245280.jpg'],
            ['nama_menu' => 'Nasi Merah & Ikan Panggang Madu', 'deskripsi' => 'Nasi merah dengan fillet ikan panggang bumbu madu & bawang putih, dan sayur kangkung.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 460, 'protein' => 30, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://www.yourultimatemenu.com/wp-content/uploads/2020/07/Honey-Garlic-Salmon-1466px.jpg'],
            ['nama_menu' => 'Tuna Sandwich Roti Gandum', 'deskripsi' => 'Roti gandum utuh, isian tuna in water, alpukat, dan selada.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 400, 'protein' => 30, 'karbohidrat' => 40, 'lemak' => 15, 'gambar' => 'https://hypeabis.id/assets/content/20230524071423000000IMG7059.jpeg'],
            ['nama_menu' => 'Nasi Putih & Tumis Udang Sayur Bening', 'deskripsi' => 'Nasi putih dengan tumis udang dan sayuran kuah bening kaldu (non-santan).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 450, 'protein' => 25, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://awsimages.detik.net.id/community/media/visual/2025/10/17/tumis-labu-siam-dan-udang-1760709673483_169.jpeg?w=600&q=90'],
            ['nama_menu' => 'Pasta Kuah Seafood', 'deskripsi' => 'Pasta Fusilli kuah kaldu seafood, udang, cumi, rendah minyak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 430, 'protein' => 25, 'karbohidrat' => 50, 'lemak' => 15, 'gambar' => 'https://image.idntimes.com/post/20221021/fromandroid-68b541457160603132e706e0959d19e3.jpg'],
            ['nama_menu' => 'Nasi & Ayam Panggang Rosemary', 'deskripsi' => 'Nasi dengan dada ayam panggang bumbu rosemary dan brokoli kukus.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 440, 'protein' => 35, 'karbohidrat' => 40, 'lemak' => 16, 'gambar' => 'https://a-cdn.sindonews.net/dyn/620/content/2017/09/13/185/1239099/yuk-buat-ayam-panggang-dengan-daun-rosemary-uN5-thumb.jpg'],
            ['nama_menu' => 'Oatmeal Savory dengan Salmon', 'deskripsi' => 'Oatmeal asin dengan fillet salmon panggang dan nori.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 490, 'protein' => 30, 'karbohidrat' => 40, 'lemak' => 22, 'gambar' => 'https://www.quakeroats.com/sites/quakeroats.com/files/2024-08/miso-salmon-steel-cut-oat-bowl.jpg'],
            ['nama_menu' => 'Tumis Ati Ampela & Nasi', 'deskripsi' => 'Nasi dengan tumis ati ampela dan cah sawi hijau.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 460, 'protein' => 30, 'karbohidrat' => 45, 'lemak' => 18, 'gambar' => 'https://cdn-brilio-net.akamaized.net/news/2021/10/06/214734/1574172-1000xauto-kreasi-tumis-ati-ampela.jpg'],
            ['nama_menu' => 'Burger Vegan Jamur Tiram', 'deskripsi' => 'Roti gandum dengan patty jamur tiram, keju rendah lemak, dan selada.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 420, 'protein' => 20, 'karbohidrat' => 50, 'lemak' => 16, 'gambar' => 'https://www.veganfoodandliving.com/wp-content/uploads/2022/09/Vegan-King-Oyster-Mushroom-Burger-820px.jpg'],
            ['nama_menu' => 'Nasi Telur Dadar Jamur', 'deskripsi' => 'Nasi dengan telur dadar 2 butir, diisi jamur dan sayuran.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 410, 'protein' => 18, 'karbohidrat' => 50, 'lemak' => 16, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1oy9NE81MA4eKH5rW4ygsKxVocf2MuZYUJA&s'],
            ['nama_menu' => 'Kentang Rebus Ayam Jamur', 'deskripsi' => 'Kentang rebus dengan suwiran ayam dan jamur tumis kecap.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 450, 'protein' => 25, 'karbohidrat' => 55, 'lemak' => 15, 'gambar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRIJoRHr2LQfat0lHSCeZr27hyQIbKfv7kXg&s'],
            ['nama_menu' => 'Nasi Bakar Ayam Suwir', 'deskripsi' => 'Nasi yang dibakar dengan isian ayam suwir, lauk telur asin (1/2 butir).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 500, 'protein' => 28, 'karbohidrat' => 55, 'lemak' => 20, 'gambar' => 'https://static.promediateknologi.id/crop/0x627:1080x1350/0x0/webp/photo/p2/74/2025/05/29/Screenshot_20250529_121510-1299912961.jpg'],
            ['nama_menu' => 'Pecel Sayur Tempe Kuah Nasi', 'deskripsi' => 'Pecel sayur dengan kuah tempe (protein nabati), disajikan dengan nasi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 450, 'protein' => 20, 'karbohidrat' => 60, 'lemak' => 15, 'gambar' => 'https://image.idntimes.com/post/20210831/resepmudahkita-1630382175600437-6422f1d69b5df4d1e79dabb3db8c1339.jpg'],
            ['nama_menu' => 'Sup Asparagus Kepiting Nasi', 'deskripsi' => 'Semangkuk sup asparagus dan kepiting dengan nasi.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 490, 'protein' => 25, 'karbohidrat' => 45, 'lemak' => 25, 'gambar' => 'https://asset.kompas.com/crops/ew-iAv_HT4PaW3R5PANcAX1OFcM=/0x0:0x0/1200x800/data/photo/2020/04/22/5ea05825aacae.jpeg'],
            ['nama_menu' => 'Sayur Bening Kentang', 'deskripsi' => 'Sayur bening bayam, disajikan dengan kentang rebus kecil (50g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 260, 'protein' => 7, 'karbohidrat' => 45, 'lemak' => 5, 'gambar' => 'https://cdn.yummy.co.id/content-images/images/20230513/VfoN9jPBJ71BzEqbr9jFSDrRGIOgCqEP-31363833393837363934d41d8cd98f00b204e9800998ecf8427e.jpg?x-oss-process=image/resize,w_388,h_388,m_fixed,x-oss-process=image/format,webp'],
            ['nama_menu' => 'Nasi Merah Beef Teriyaki', 'deskripsi' => 'Nasi merah (120g) dengan irisan daging sapi teriyaki (80g) dan sawi putih.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 30, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://img-global.cpcdn.com/recipes/1e1f89c91446ca01/680x781cq80/chicken-teriyaki-mushroom-nasi-merah-foto-resep-utama.jpg'],
            ['nama_menu' => 'Lumpia Basah Sayuran Ayam', 'deskripsi' => 'Lumpia basah porsi besar berisi rebung, tauge, dan ayam cincang.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 420, 'protein' => 20, 'karbohidrat' => 55, 'lemak' => 14, 'gambar' => 'https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-content/uploads/2023/08/04051337/Praktis-dan-Simpel-Ini-Cara-Membuat-Lumpia-Basah-di-Rumah.jpg.webp'],
            ['nama_menu' => 'Dada Ayam Kukus & Salad', 'deskripsi' => 'Dada ayam kukus (100g) dengan salad sayuran segar dan dressing balsamic.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 310, 'protein' => 35, 'karbohidrat' => 10, 'lemak' => 16, 'gambar' => 'https://akcdn.detik.net.id/visual/2023/11/20/ilustrasi-dada-ayam_169.jpeg?w=650'],
            ['nama_menu' => 'Pasta Fettuccine Udang Tomat', 'deskripsi' => 'Pasta fettuccine (70g kering) dengan udang dan saus tomat ringan.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 460, 'protein' => 25, 'karbohidrat' => 55, 'lemak' => 18, 'gambar' => 'https://png.pngtree.com/thumb_back/fh260/background/20250602/pngtree-pappardelle-fettuccine-with-shrimp-on-a-white-plate-against-background-image_17379377.jpg'],
            ['nama_menu' => 'Tofu Scramble & Paprika', 'deskripsi' => 'Tahu orak-arik (scramble) dengan paprika, tanpa minyak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 240, 'protein' => 15, 'karbohidrat' => 15, 'lemak' => 14, 'gambar' => 'https://www.healthyfood.com/healthy-recipes/smoky-paprika-tofu-scramble/'],
            ['nama_menu' => 'Orak-Arik Sayur Tahu Nasi', 'deskripsi' => 'Nasi (120g) dengan orak-arik sayur (wortel, buncis) dan tahu putih.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 430, 'protein' => 16, 'karbohidrat' => 50, 'lemak' => 18, 'gambar' => 'https://asset.kompas.com/crops/WKrz2GbcHcLhJkmgcXF_19VDLCw=/0x307:667x752/1200x800/data/photo/2023/05/23/646c99fda4eeb.jpeg'],
            ['nama_menu' => 'Sup Miso Tofu Salmon Nasi', 'deskripsi' => 'Sup Miso dengan potongan tahu, rumput laut, dan potongan kecil salmon, dengan nasi (80g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 470, 'protein' => 30, 'karbohidrat' => 35, 'lemak' => 25, 'gambar' => 'https://img-global.cpcdn.com/recipes/edcbaaad49f6f896/680x781f0.501614_0.5_1.0q80/sup-tofu-salmon-ala-resto-jepang-foto-resep-utama.jpg'],
            ['nama_menu' => 'Nasi Kuning Ayam Suwir', 'deskripsi' => 'Nasi kuning (120g) dengan ayam suwir, abon kedelai, dan irisan timun.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 460, 'protein' => 25, 'karbohidrat' => 55, 'lemak' => 18, 'gambar' => 'https://img.inews.co.id/media/1200/files/inews_new/2023/03/14/Cara_membuat_nasi_kuning_sederhana.jpg'],
            ['nama_menu' => 'Tongseng Tahu Jamur Nasi', 'deskripsi' => 'Tongseng tahu dan jamur (tanpa santan kental/daging), disajikan dengan nasi (100g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 410, 'protein' => 15, 'karbohidrat' => 55, 'lemak' => 15, 'gambar' => 'https://image.idntimes.com/post/20201217/image-c983f087399fb5d3f02a2fff4e6245fd.jpg?tr=w-1200,f-webp,q-75&width=1200&format=webp&quality=75'],
            ['nama_menu' => 'Nasi Putih & Ayam Mentega Sehat', 'deskripsi' => 'Nasi (120g) dengan ayam mentega (dada, minyak sedikit) dan sayur.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 35, 'karbohidrat' => 45, 'lemak' => 20, 'gambar' => 'https://png.pngtree.com/png-clipart/20250103/original/pngtree-butter-chicken-served-with-rice-png-image_19281137.png'],
            ['nama_menu' => 'Sup Salmon Brokoli & Ubi', 'deskripsi' => 'Sup bening fillet salmon (80g) dan brokoli, disajikan dengan ubi jalar rebus (80g).', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 390, 'protein' => 30, 'karbohidrat' => 35, 'lemak' => 15, 'gambar' => 'https://fedandfit.com/wp-content/uploads/2022/02/230516_chicken-quinoa-bowls-7.jpg'],
            ['nama_menu' => 'Bubur Ayam Kacang', 'deskripsi' => 'Bubur beras dengan suwiran ayam, kacang, dan 1/2 telur rebus.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 420, 'protein' => 20, 'karbohidrat' => 60, 'lemak' => 12, 'gambar' => 'https://asset.kompas.com/crops/Xd5p_ptNeya-LsNQ0CxWomaW0KI=/0x0:1000x667/1200x800/data/photo/2020/07/11/5f09e008e7fee.jpg'],
            ['nama_menu' => 'Wrap Tuna Sayur Ubi', 'deskripsi' => 'Tortilla gandum berisi tuna (in water), selada, dan ubi rebus (50g) sebagai isian.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 450, 'protein' => 30, 'karbohidrat' => 45, 'lemak' => 18, 'gambar' => 'https://www.killingthyme.net/wp-content/uploads/2020/11/tuna-veggie-wrap-4.jpg'],
            ['nama_menu' => 'Nasi Goreng Shirataki Seafood Sehat', 'deskripsi' => 'Nasi shirataki goreng (porsi sedang) dengan udang, cumi, dan sayuran, rendah minyak.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 25, 'karbohidrat' => 60, 'lemak' => 18, 'gambar' => 'https://img-cdn.medkomtek.com/FSu9JgZ4kCsuZDg1hRMwLXuhtK0=/510x395/smart/filters:quality(100):format(webp)/article/AGOBTY4NKWtnKaLgME_LY/original/094913400_1574998128-Coba-Konsumsi-Nasi-Shirataki-Amankah-untuk-Diet-By-Colnihko-Shutterstock_306444554.jpg'],
        ];
      
              // ==========================================
        // 1. MENU AWAL (20 ITEM) - Kategori Campur
        // ==========================================
        $menus_awal = [
            ['nama_menu' => 'Nasi Goreng Telur', 'deskripsi' => 'Nasi goreng simple dengan telur orak-arik, cocok untuk makan siang cepat.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 520, 'protein' => 18, 'karbohidrat' => 65, 'lemak' => 20, 'gambar' => 'https://images.pexels.com/photos/32938733/pexels-photo-32938733.jpeg'],
            ['nama_menu' => 'Ayam Bakar Madu', 'deskripsi' => 'Ayam bakar manis gurih dengan olesan madu dan rempah.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 480, 'protein' => 35, 'karbohidrat' => 25, 'lemak' => 15, 'gambar' => 'https://asset.kompas.com/crops/N8WTCiVClutwEkjIgCykYbt1e2Q=/142x72:863x553/1200x800/data/photo/2022/09/27/633297e88244b.jpg'],
            ['nama_menu' => 'Soto Ayam', 'deskripsi' => 'Kuah hangat dengan suwiran ayam dan sayuran, rendah lemak.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 390, 'protein' => 28, 'karbohidrat' => 20, 'lemak' => 9, 'gambar' => 'https://healthybelly.s3.amazonaws.com/product/media_1738841131_0.webp'],
            ['nama_menu' => 'Nasi Uduk Komplit', 'deskripsi' => 'Nasi uduk gurih dengan lauk telur, tempe, dan sambal.', 'kategori' => 'sarapan', 'tipe_makanan' => 'non_vegan', 'kalori' => 560, 'protein' => 16, 'karbohidrat' => 72, 'lemak' => 22, 'gambar' => 'https://images.pexels.com/photos/5963873/pexels-photo-5963873.jpeg'],
            ['nama_menu' => 'Power Beef Bowl', 'deskripsi' => 'Nasi merah, daging sapi tumis lada hitam, telur rebus, dan brokoli.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 650, 'protein' => 45, 'karbohidrat' => 60, 'lemak' => 20, 'gambar' => 'https://wearefeels.com/wp-content/uploads/2024/08/Beef-power-bowl.webp'],
            ['nama_menu' => 'Salad Wrap Ayam Panggang', 'deskripsi' => 'Tortilla gandum isi dada ayam panggang, selada segar, dan dressing rendah lemak.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 320, 'protein' => 25, 'karbohidrat' => 30, 'lemak' => 8, 'gambar' => 'https://img.freepik.com/foto-premium/wrap-ayam-panggang-tertutup-di-latar-belakang-putih-wrap-tortilla-dengan-ayam-sayuran-dan-salad_817921-53360.jpg'],
            ['nama_menu' => 'Nasi Merah Tempe Orek', 'deskripsi' => 'Pilihan menu vegan dengan tempe orek manis pedas dan nasi merah.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 410, 'protein' => 16, 'karbohidrat' => 56, 'lemak' => 9, 'gambar' => 'https://img-global.cpcdn.com/recipes/ed3a06fff363946b/1200x630cq80/photo.jpg'],
            ['nama_menu' => 'Salad Sayur Segar', 'deskripsi' => 'Salad kombinasi sayur hijau, tomat ceri, dan dressing ringan.', 'kategori' => 'snack', 'tipe_makanan' => 'vegan', 'kalori' => 180, 'protein' => 5, 'karbohidrat' => 15, 'lemak' => 8, 'gambar' => 'https://asset.kompas.com/crops/vbUoFm_zyz80BXnD1eVXy2j_Nl8=/0x0:780x390/750x500/data/photo/2013/03/18/0936436-salad-sayuran-780x390.jpg'],
            ['nama_menu' => 'Sup Jagung Sayur', 'deskripsi' => 'Sup hangat jagung dan sayur, cocok untuk menu diet.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 220, 'protein' => 6, 'karbohidrat' => 30, 'lemak' => 7, 'gambar' => 'https://akcdn.detik.net.id/visual/2020/01/12/c3396348-c3c9-4ea2-a074-487916a21c6f_43.jpeg?w=720&q=90'],
            ['nama_menu' => 'Peanut Butter Banana Toast', 'deskripsi' => 'Roti gandum bakar dengan selai kacang alami dan potongan pisang.', 'kategori' => 'snack', 'tipe_makanan' => 'vegan', 'kalori' => 450, 'protein' => 15, 'karbohidrat' => 55, 'lemak' => 18, 'gambar' => 'https://www.aheadofthyme.com/wp-content/uploads/2018/02/peanut-butter-banana-toast.jpg'],
            ['nama_menu' => 'Oatmeal Buah', 'deskripsi' => 'Oatmeal dengan topping buah segar, menu sarapan rendah lemak.', 'kategori' => 'sarapan', 'tipe_makanan' => 'vegan', 'kalori' => 260, 'protein' => 7, 'karbohidrat' => 46, 'lemak' => 5, 'gambar' => 'https://images.pexels.com/photos/9027530/pexels-photo-9027530.jpeg'],
            ['nama_menu' => 'Smoothie Pisang Kacang', 'deskripsi' => 'Makanan tinggi energi untuk sarapan cepat.', 'kategori' => 'snack', 'tipe_makanan' => 'vegan', 'kalori' => 250, 'protein' => 10, 'karbohidrat' => 35, 'lemak' => 6, 'gambar' => 'https://www.darngoodveggies.com/wp-content/uploads/2021/08/Banana-Smoothie-Bowl-5-scaled.jpg'],
            ['nama_menu' => 'Nasi Campur Bali', 'deskripsi' => 'Menu khas Bali dengan lauk lengkap dan sambal matah.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'non_vegan', 'kalori' => 620, 'protein' => 24, 'karbohidrat' => 74, 'lemak' => 24, 'gambar' => 'https://img-global.cpcdn.com/recipes/bbdc38a8c3206126/680x781f0.5_0.552021_1.0q80/nasi-campur-bali-foto-resep-utama.jpg'],
            ['nama_menu' => 'Ayam Teriyaki Panggang', 'deskripsi' => 'Dada ayam dipanggang dengan saus teriyaki homemade, disajikan dengan sayuran kukus.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 350, 'protein' => 32, 'karbohidrat' => 20, 'lemak' => 10, 'gambar' => 'https://asset.kompas.com/crops/-b8jj61ACSloKe1JGBgAGrgXDdU=/3x0:700x465/1200x800/data/photo/2020/12/17/5fdacb3363f6a.jpg'],
            ['nama_menu' => 'Pecel Madiun Komplit', 'deskripsi' => 'Aneka sayuran rebus dengan bumbu kacang, tahu, tempe, dan nasi merah.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 520, 'protein' => 20, 'karbohidrat' => 60, 'lemak' => 22, 'gambar' => 'https://d1vbn70lmn1nqe.cloudfront.net/prod/wp-content/uploads/2023/07/28023918/Ini-Cara-Membuat-Nasi-Pecel-Madiun-yang-Menggugah-Selera-.jpg.webp'],
            ['nama_menu' => 'Gado-Gado', 'deskripsi' => 'Sayuran rebus dengan bumbu kacang, tinggi serat dan mengenyangkan.', 'kategori' => 'makan_siang', 'tipe_makanan' => 'vegan', 'kalori' => 360, 'protein' => 12, 'karbohidrat' => 30, 'lemak' => 18, 'gambar' => 'https://images.pexels.com/photos/31336118/pexels-photo-31336118.jpeg'],
            ['nama_menu' => 'Bubur Kacang Hijau', 'deskripsi' => 'Camilan hangat dengan santan, cocok sore hari.', 'kategori' => 'snack', 'tipe_makanan' => 'vegan', 'kalori' => 210, 'protein' => 7, 'karbohidrat' => 34, 'lemak' => 4, 'gambar' => 'https://allofresh.id/blog/wp-content/uploads/2023/07/cara-membuat-bubur-kacang-hijau-2-2.jpg'],
            ['nama_menu' => 'Nasi Tim Ayam Merah', 'deskripsi' => 'Nasi tim beras merah lembut dengan topping tumis dada ayam jamur kecap dan kuah kaldu bening.', 'kategori' => 'sarapan', 'tipe_makanan' => 'non_vegan', 'kalori' => 380, 'protein' => 26, 'karbohidrat' => 45, 'lemak' => 10, 'gambar' => 'https://cdn.grid.id/crop/0x0:0x0/filters:format(webp):quality(100)/photo/2023/06/19/resep-nasi-merah-tim-ayam-sayur-20230619043905.jpg'],
            ['nama_menu' => 'Stir Fry Tofu & Sayur Hijau', 'deskripsi' => 'Tahu tinggi protein ditumis dengan brokoli, buncis, dan bayam.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'vegan', 'kalori' => 210, 'protein' => 14, 'karbohidrat' => 16, 'lemak' => 8, 'gambar' => 'https://www.bakedbymelissa.com/cdn/shop/articles/20250505061954-8_d0cff26f-fc3c-43f4-ac25-9195d318734e.png?v=1746725892'],
            ['nama_menu' => 'Sup Ayam Jahe & Sayur', 'deskripsi' => 'Sup bening ayam kampung dengan wortel, buncis, dan aroma jahe hangat.', 'kategori' => 'makan_malam', 'tipe_makanan' => 'non_vegan', 'kalori' => 250, 'protein' => 22, 'karbohidrat' => 15, 'lemak' => 8, 'gambar' => 'https://www.dapurkobe.co.id/wp-content/uploads/sop-ayam-bening-jahe.jpg'],
        ];

        // GABUNGKAN SEMUA MENU
        $all_menus = array_merge($menus_awal, $maintain_siang, $weightloss_siang, $bulking_siang, $maintain_malam, $weightloss_malam, $bulking_malam);

        // INSERT KE DATABASE
        foreach ($all_menus as $menu) {
            Menu::create($menu);
        }
    }
}